import { Predictions } from './predictions';
import { AuditInfo } from './auditInfo';
import { ContractSecurityInfo } from './contractSecurityInfo';
import { HackInfo } from './hackInfo';
import { DepegAlert } from './depegAlert';

export interface Pool {
  hacks: HackInfo[];
  depegAlerts: DepegAlert[];
  auditInfo: AuditInfo | null;
  contractSecurity: ContractSecurityInfo[];
  url: string | null;
  chain: string;
  project: string;
  symbol: string;
  dataSource: string;
  tvlUsd: number;
  apyBase: number | null;
  apyReward: number | null;
  apy: number;
  rewardTokens: string[] | null;
  pool: string;
  apyPct1D: number | null;
  apyPct7D: number | null;
  apyPct30D: number | null;
  stablecoin: boolean;
  ilRisk: string;
  exposure: string;
  predictions: Predictions;
  poolMeta: string | null;
  mu: number;
  sigma: number;
  count: number;
  outlier: boolean;
  underlyingTokens: string[] | null;
  il7d: number | null;
  apyBase7d: number | null;
  apyMean30d: number;
  volumeUsd1d: number | null;
  volumeUsd7d: number | null;
  apyBaseInception: number | null;
}
