CREATE TABLE [DefiLlama].[Pool]
(
  [PoolId] NVARCHAR(100) NOT NULL,
  [Chain] NVARCHAR(100) NOT NULL,
  [Project] NVARCHAR(100) NOT NULL,
  [Symbol] NVARCHAR(200) NOT NULL,
  [TvlUsd] FLOAT(53) NOT NULL,
  [ApyBase] FLOAT(53) NULL,
  [ApyReward] FLOAT(53) NULL,
  [Apy] FLOAT(53) NOT NULL,
  [ApyPct1D] FLOAT(53) NULL,
  [ApyPct7D] FLOAT(53) NULL,
  [ApyPct30D] FLOAT(53) NULL,
  [Stablecoin] BIT NOT NULL,
  [IlRisk] NVARCHAR(50) NOT NULL,
  [Exposure] NVARCHAR(50) NULL,
  [PredictedClass] NVARCHAR(50) NULL,
  [PredictedProbability] FLOAT(53) NULL,
  [BinnedConfidence] FLOAT(53) NULL,
  [PoolMeta] NVARCHAR(MAX) NULL,
  [Mu] FLOAT(53) NOT NULL,
  [Sigma] FLOAT(53) NOT NULL,
  [Count] INT NOT NULL,
  [Outlier] BIT NOT NULL,
  [Il7d] FLOAT(53) NULL,
  [ApyBase7d] FLOAT(53) NULL,
  [ApyMean30d] FLOAT(53) NOT NULL,
  [VolumeUsd1d] FLOAT(53) NULL,
  [VolumeUsd7d] FLOAT(53) NULL,
  [ApyBaseInception] FLOAT(53) NULL,
  [DateCreated] DATETIMEOFFSET NOT NULL,
  [DateUpdated] DATETIMEOFFSET NOT NULL,
  [DataDate] DATETIMEOFFSET NULL,
  CONSTRAINT [PK_DefiLlama_Pool] PRIMARY KEY ([PoolId])
);
