#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Run Prettier on all staged files
npx prettier --write .

# Run tests
npm test

# Fix package-lock.json registry URL
sed -i "s|https://npm.markridgwell.com/|https://registry.npmjs.org/|g" package-lock.json

# Stage the fixed package-lock.json if it changed
git add package-lock.json
